services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  webapplication_docker.ui:
    image: ${DOCKER_REGISTRY-}webapplicationdockerui
    container_name: app
    build:
      context: .
      dockerfile: WebApplication_Docker.UI/Dockerfile
    ports:
      - "1001:8081"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    depends_on:
      - db
    volumes:
      - ~/.aspnet/https:/https:ro
volumes:
  postgres_data: